apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out ./kubernetes/
    kompose.version: 1.26.1 (a9d05d509)
    kompose.volume.type: configMap
  creationTimestamp: 2022-07-17T07:20:50.52Z
  labels:
    io.kompose.service: mosquitto
  name: mosquitto
spec:
  ports:
    - name: "1883"
      port: 1883
      targetPort: 1883
  selector:
    io.kompose.service: mosquitto
status:
  loadBalancer: {}
