apiVersion: v1
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  creationTimestamp: 2022-07-17T07:20:50.52Z
  labels:
    io.kompose.service: mosquitto
  name: mosquitto-cm0
