apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: 2022-07-17T07:20:50.52Z
  labels:
    io.kompose.service: redisdata
  name: redisdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
