apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  
  labels:
    io.kompose.service: chirpstack-gateway-bridge-eu868-claim0
  name: chirpstack-gateway-bridge-eu868-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
