apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out ./kubernetes/
    kompose.version: 1.26.1 (a9d05d509)
    kompose.volume.type: configMap
  creationTimestamp: 2022-07-17T07:20:50.52Z
  labels:
    io.kompose.service: chirpstack-gateway-bridge-eu868
  name: chirpstack-gateway-bridge-eu868
spec:
  ports:
    - name: "1700"
      port: 1700
      targetPort: 1700
  selector:
    io.kompose.service: chirpstack-gateway-bridge-eu868
status:
  loadBalancer: {}
